### ISSUE TITLE
restaging does not preserve replicas

### ISSUE THREAD

**Issue by gscteam** [irods/irods_capability_storage_tiering#125]
Hi, 

It seems that the preserver replicas option is not working when restaging data. I am preparing a PR for this, but I wanted to check there was not a design feature I was missing. 

We want the replica to stay on the archive tier and get restage on the fast tier. So preserver replicas enabled on the archive tier should achieve that.

**Comment by trel** [comment]
is this the same as #92?    does it work if trees are not in use?

**Comment by gscteam** [comment]
No it is not, issue 92 is about re-tiering ( migrating to the next tier). This one is about  preserve the replicate when restaging is triggered (by an iget), the default behavior is to copy to the minimum_restage_tier and trim the high tier(archive). So the coming commit will honor the 'preserve replica' parameter when set on the archive and prevent remigration when the object is in violation.

**Comment by trel** [comment]
Okay - Please provide a test that covers the case that is different from this test case:
  https://github.com/irods/irods_capability_storage_tiering/blob/1f537f2a84fb052664d25b7bbe2f4c201e377a95/packaging/test_plugin_storage_tiering.py#L1110

**Comment by wccropper** [comment]
@trel How do we run the test in the development docker environment? We get the following trying to execute the unified test:

# python run_unified_storage_tiering_plugin_test.py
/bin/python: No module named xmlrunner

# pip install xmlrunner
# python run_unified_storage_tiering_plugin_test.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/xmlrunner/__main__.py", line 19, in <module>
    XMLTestProgram(module=None)
  File "/usr/lib/python2.7/site-packages/xmlrunner/runner.py", line 129, in __init__
    super(XMLTestProgram, self).__init__(*args, **kwargs)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_plugin_storage_tiering'

**Comment by alanking** [comment]
I don't know that those python scripts work anymore (or at least I've never tried them). The test hook is how storage tiering is tested in our CI, so that would probably be a better script to run. I personally have found that if you just want to run tests manually at the bench, it's easiest to use the run_tests.py script from irods-server package:

```
$ su - irods
$ python scripts/run_tests.py --run_specific_test test_plugin_unified_storage_tiering
```

There is a line similar to this in the test hook: https://github.com/irods/irods_capability_storage_tiering/blob/042773f80f8080aaf12851110d0e0f9ce0aaf1ca/irods_consortium_continuous_integration_test_hook.py#L47

Hope that helps!

**Comment by wccropper** [comment]
Getting this to run consistently is proving difficult. the current steps are:

1. clean docker (using the runner from the dev env, removing default packages installed as root, clearing all dirs and creating irods user)
2. install and configure postgres
3. install default 4.2.7 server + postgres
4. complete setup.py
5. stop irods, install compiled unified storage rpm (this also requires the catch22, so enabled dev repo) and start irods
6. python scripts/run_tests.py --run_specific_test test_plugin_unified_storage_tiering
7. hangs on first test (irods.test.test_plugin_unified_storage_tiering.TestStorageTieringContinueInxMigration.test_put_gt_max_sql_rows)

test_log, rodsLog and rodsServerLog attached
[test_log.txt](https://github.com/irods/irods_capability_storage_tiering/files/4149913/test_log.txt)
[rodsLog.2020.02.01.txt](https://github.com/irods/irods_capability_storage_tiering/files/4149919/rodsLog.2020.02.01.txt)
[rodsServerLog.2020.02.01.txt](https://github.com/irods/irods_capability_storage_tiering/files/4149920/rodsServerLog.2020.02.01.txt)

**Comment by trel** [comment]
The error in the rodsLog is:

`INVALID_ANY_CAST` --> `boost::bad_any_cast: failed conversion using boost::any_cast`

```
Feb  3 19:26:36 pid:1030 remote addresses: 127.0.0.1, 172.17.0.5 ERROR: applyRule: -1822000, [-]	/irods/server/re/include/irods_re_plugin.hpp:206:irods::error irods::pluggable_rule_engine<std::__1::tuple<> >::rule_exists(const std::string &, T &, bool &) [T = std::__1::tuple<>] :  status [INVALID_ANY_CAST]  errno [] -- message [failed to extract rule_exists operation from instance [irods_rule_engine_plugin-unified_storage_tiering-instance] exception message [boost::bad_any_cast: failed conversion using boost::any_cast]]
```
