### ISSUE TITLE
Files with the character ' in the name do not tier 

### ISSUE THREAD

**Issue by darthtux** [irods/irods_capability_storage_tiering#127]
If a file with a ' in the name is placed in tier 0 it remain in tier 0 after it is in violation of the tiering policy and the tiering policy is applied.  The expected behavior is files with this character in the name would tier like other files when the tiering policy is applied.  

This is the irule command I am using
    
    irule -F example_tiering_invocation.r -r irods_rule_engine_plugin-storage_tiering-instance

this is the contents of example_tiering_invocation.r
    
    {
       "rule-engine-instance-name": "irods_rule_engine_plugin-storage_tiering-instance",
       "rule-engine-operation": "irods_policy_schedule_storage_tiering",
       "delay-parameters": "<INST_NAME>irods_rule_engine_plugin-storage_tiering-instance</INST_NAME><PLUSET>1s</PLUSET><EF>1h DOUBLE UNTIL SUCCESS OR 6   TIMES</EF>",
       "storage-tier-groups": [
           "test_tier"
       ]
    }
    INPUT null
    OUTPUT ruleExecOut

After the tiering policy is applied, repeatedly running iqstat never shows the object as moving to a different tier.  

This is the only character I have seen cause issues with the tiering policy.  I have tried files with these characters in the name without issue:  " * - _ (

**Comment by trel** [comment]
We're working on reproducing this error.

**Comment by trel** [comment]
@darthtux we couldn't reproduce the error with the refactored codebase - the test gives us confidence that the original bug is gone.   if found again, please open a new issue.
