### ISSUE TITLE
Create back-dated tag based on versions

### ISSUE THREAD

**Issue by kript** [irods/irods_capability_storage_tiering#185]
We recently got caught out because the documentation isn't obviously version specific.
(e.g. [4.2.7](https://github.com/irods/irods_capability_storage_tiering/tree/fd0c65c1a6f3940ff232311465556ae8feadc434#rulebase-configuration) ); would it be possible to go back through and tag the commits that make the assorted versions so that the correct 'point in time' can be referenced please?

**Comment by trel** [comment]
I think this is already done as part of shipping a release?

https://github.com/irods/irods_capability_storage_tiering/releases

Is there something else you'd like to see?

**Comment by kript** [comment]
So it is! Clearly I was looking in the wrong place, sorry!
