### ISSUE TITLE
Avoid using "DOUBLE" in default delay parameters and example tiering rule

### ISSUE THREAD

**Issue by alanking** [irods/irods_capability_storage_tiering#191]
The default delay parameters for migration and example storage tiering rule using the "DOUBLE" keyword in the execution frequency hint. As this is known to be faulty, we should avoid using it and its usage replaced with "REPEAT".

Additionally, the example rule can have its delay parameters reduced in time (i.e. 1 hour is a very long time for an example/demo). Despite the fact that it is more in line with a real world use case, it make demonstrations and testing annoying to work with.

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/5964

**Comment by alanking** [comment]
Still need to update the README and the default delay parameters for data migration:
https://github.com/irods/irods_capability_storage_tiering/blob/a3a6baab10f2f456fcfea315bfb490636198f034/storage_tiering_configuration.hpp#L32

I've also noticed a file called sample_configuration.json in this repository which contains the DOUBLE keyword, but nothing seems to be using this. We can probably remove this file.

**Comment by trel** [comment]
> We can probably remove this file

agreed - it appears out of date - and the README.md should have all that type of information in it already.

**Comment by trel** [comment]
https://github.com/irods/irods/issues/5964 has now been fixed in 4.3.1

**Comment by alanking** [comment]
Removing the 4-2-stable checkbox - we can cherry-pick this and many other fixes if/when another 4.2 release is required.
