### ISSUE TITLE
add storage_tiering_data_transfer_protocol option to plugin_specific_configuration

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_storage_tiering#20]
The new parameter could be...
```
"plugin_specific_configuration": {
     "storage_tiering_data_transfer_protocol" : "default"
}
```
or

```
"plugin_specific_configuration": {
     "storage_tiering_data_transfer_protocol" : "<other protocol"
}
```
If the code sees this setting set to default, it will use the default irods tcp protocol for transfer of data between tiers.  but if it is set to any other installed protocols such as UDR, ASCP, GridFTP etc that's been used in the company and tested to get high data transfer rate (e.g. 30 gbps in 100 gb network), then irods storage tiering can be used to capture metadata, trigger the data movement between tiers in the tier group, using specified protocol.

**Comment by jasoncoposky** [comment]
The multipart plugin will support pluggable data transport protocols which should be available transparently.  This plugin should introspect and determine if multipart is available and leverage that option for data transport.
