### ISSUE TITLE
Plugin doesn't identify itself to `ips`

### ISSUE THREAD

**Issue by kript** [irods/irods_capability_storage_tiering#208]
On 4.2.7, with `irods-rule-engine-plugin-storage-tiering   2.7.0`, when the `irodsServer` processes are running, they appear as `UNKNOWN` in the `ips` report.

It would be helpful if they identified the plugin that was being used, in some way.

**Comment by alanking** [comment]
Please see comment in indexing: https://github.com/irods/irods_capability_indexing/issues/121#issuecomment-1151369233 I think these issues are very similar.

**Comment by trel** [comment]
Can now be closed - it should now appear as the delay server in `ips`.

Due to https://github.com/irods/irods/issues/5264.
