### ISSUE TITLE
Track tier group for restage when using a common archive

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_capability_storage_tiering#48]
When storage tiering is configured to use a common archive tier, once the file goes to the common archive, it is not clear which tier group should be used when restaging the file.

It would make sense to track the initial group that the file was written to so that when it is restaged it can go to the appropriate resource that is in that group..

**Comment by trel** [comment]
additionally... replicas of the same file could be in different groups?

and then would all end up in the same archive?
